version: '3.8'
services:
  database:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: candle
      POSTGRES_PASSWORD: candle
      POSTGRES_DB: planting

volumes:
  db-data: